name: code_asset_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  benchmark_harness: ^2.4.0
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  native_toolchain_c: ^0.17.4
  # path: ^1.9.0

dev_dependencies:

  ffigen: ^20.1.1
  lints: ^6.0.0
  logging: ^1.3.0
  test: ^1.25.6

hooks:
  build: hooks/build.dart
